"""Initial migration

Revision ID: fe792c6ec011
Revises: 
Create Date: 2026-06-19 13:00:30.499822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe792c6ec011'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'brand_assets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('filepath', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_type', sa.String(length=100), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_assets_id'), 'brand_assets', ['id'], unique=False)
    
    op.create_table(
        'generated_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('prompt', sa.String(length=500), nullable=False),
        sa.Column('negative_prompt', sa.String(length=500), nullable=True),
        sa.Column('filepath', sa.String(length=500), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('steps', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_brand_assets_id'), table_name='brand_assets')
    op.drop_table('brand_assets')
    # ### end Alembic commands ###
